services:
  lint:
    image: buildkite/plugin-linter:v2.1.0
    command: ['--id', 'lucaswilric/tool-versions-env']
    volumes:
      - ".:/plugin:ro"

  tests:
    image: buildkite/plugin-tester:v4.2.0
    volumes:
      - ".:/plugin:ro"
