name: "asdf/mise info"
description: Sets environment variables with versions from asdf & mise configuration
author: https://github.com/buildkite/
requirements: ["buildkite-agent", "awk"]
configuration:
  properties:
    source:
      type: string
#   additionalProperties: false
